version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - run: node --version
      - run: npm --version

      - checkout

      - restore_cache:
          keys:
            - node_modules-{{checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
          key: node_modules-{{checksum "package-lock.json"}}
          paths:
            - node_modules

      - run: npm run lint
      - run: npm run test
